#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

plugin_main_cmd() {
  declare desc="shows details about locally installed plugins"
  local cmd="plugin"
  trigger-plugn version
  trigger-plugn list
}

plugin_main_cmd "$@"
