#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

plugin_update_cmd() {
  declare desc="updates plugin to optional committish and calls update plugin trigger via command line"
  local cmd="plugin:update"
  if [[ -n "$2" ]]; then
    local PLUGIN="$2"
    local PLUGIN_COMMITTISH="$3"
    export PLUGIN_PATH="$PLUGIN_COMMUNITY_PATH"
    trigger-plugn update "$PLUGIN" "$PLUGIN_COMMITTISH"
  fi
  trigger-plugn trigger update
}

plugin_update_cmd "$@"
